### ISSUE TITLE
Fails with Gradle 4.9

### ISSUE THREAD

**Issue by shollander** [mdietrichstein/gradle-offline-dependencies-plugin#17]
When attempting to use the `gradle-offline-dependencies-plugin` with Gradle 4.9 I get the following error:

> groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.internal.component.external.model.DefaultModuleComponentIdentifier(java.lang.String, java.lang.String, java.lang.String)
> at io.pry.gradle.offline_dependencies.UpdateOfflineRepositoryTask$_collectRepositoryFiles_closure4.doCall(UpdateOfflineRepositoryTask.groovy:135)
> at com.sun.proxy.$Proxy59.accept(Unknown Source)
> at io.pry.gradle.offline_dependencies.UpdateOfflineRepositoryTask.collectRepositoryFiles(UpdateOfflineRepositoryTask.groovy:133)
> io.pry.gradle.offline_dependencies.UpdateOfflineRepositoryTask.withRepositoryFiles(UpdateOfflineRepositoryTask.groovy:310)
> io.pry.gradle.offline_dependencies.UpdateOfflineRepositoryTask.run(UpdateOfflineRepositoryTask.groovy:57)

**Comment by tonit** [comment]
yep, can confirm it does not work with gradle 4.9 onwards. 
Can you go around using internal api for this?
I actually had some discussion with the gradle team about this at https://github.com/gradle/gradle/issues/5950. It is wether or not this should be better supported by core gradle. You plugin should not require internal api. Otherwise I'd open a ticket at Gradle about it.

**Comment by jdchn** [comment]
Appears to be broken due to: https://github.com/gradle/gradle/commit/cb8d1762066084109168ceabbc50cb98869e889f which modifies the  [`DefaultModuleComponentIdentifier`](https://github.com/gradle/gradle/blob/1716bdf6dedb114167919650ebbbfa25b55177de/subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultModuleComponentIdentifier.java#L29) constructor. 

The naive fix is to use [`DefaultModuleIdentifier`](https://github.com/gradle/gradle/blob/01403dbe1fb4417c3f490043ef2b75b1feac8b7f/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultModuleIdentifier.java), but this would break compatibility with Gradle releases prior to 4.9.

**Comment by swegner** [comment]
Any update on this?

Our project (Apache Beam) [uses `updateOfflineRepository`](https://github.com/apache/beam/blob/ddbebc7a32cbbb9e6a9676d0051f7a870d316199/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L595), and are broken with Gradle 4.9: [BEAM-5631](https://issues.apache.org/jira/browse/BEAM-5631). Our workaround is to downgrade to Gradle 4.8 before running this task.

**Comment by realPyR3X** [comment]
Hoping for a fix to this! Any update?

**Comment by mdietrichstein** [comment]
Sorry for the delay, haven't had much time to work on the project over the last few months.

I have released version 0.5.0 of the plugin which has been tested with Gradle 5.1 and it seems to work now. Please let me know if the issue is resolved for you guys as well.
